name: Feature Request
description: Request a new feature for one of our packages
labels: ['enhancement', 'needs-triage']
body:
  - type: dropdown
    id: package
    attributes:
      label: Affected Package
      description: Which package should this feature be added to?
      options:
        - '@opensourceframework/next-csrf'
        - '@opensourceframework/next-images'
        - '@opensourceframework/critters'
        - New Package Suggestion
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here