name: Security Vulnerability
description: Report a security vulnerability
labels: ['security']
body:
  - type: markdown
    attributes:
      value: |
        **Please do not report security vulnerabilities through public GitHub issues.**
        
        Instead, please report them through GitHub Security Advisories.
        
        Go to: Security > Report a vulnerability
        
        Or visit: https://github.com/opensourceframework/opensourceframework/security/advisories/new